# -----------------------------------------------------
# Autostart
# -----------------------------------------------------
### Setup Quickshell
exec-once = qs
exec-once = qs -c ~/.config/quickshell/overview

### Load notif daemon
exec-once = swaync &

### Load Wallpaper
exec-once = swww-daemon

### Load Launcher
exec-once = vicinae server

### Using swayidle to start swaylock
exec-once = hypridle

### Load cliphist history
exec-once = wl-paste --watch cliphist store

### Firewall
exec-once = /usr/lib/polkit-kde-authentication-agent-1


# AutoRun Apps
exec-once = kdeconnect-indicator &
#exec-once = nm-applet --indicator &

